[workspace]
members = ["lexer", "parser"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde_json = "1.0.124"
serde = { version = "1.0.206", features = ["derive"] }
bumpalo = { version = "3.16.0", features = ["collections", "boxed"] }
