[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
lexer = { path = "../lexer" }
lazy_static = "1.4.0"
string_cache = "0.8.4"

[dev-dependencies]
pretty_assertions = "1.4.0"
